FROM eclipse-temurin:17-alpine

WORKDIR /mybatis-project-backend

COPY target/mybatis-project-backend-0.0.1-SNAPSHOT.jar /mybatis-project-backend

CMD ["java", "-jar", "mybatis-project-backend-0.0.1-SNAPSHOT.jar"]
