package com.allxone.coinmarket.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor

public class Coins {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coins.id
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coins.name
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coins.symbol
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coins.coinmarket_id
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    private Integer coinmarketId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coins.quantity
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    private Double quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coins.user_id
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coins.created_at
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coins.updated_at
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    private Date updatedAt;

    private Double price;

    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coins.id
     *
     * @return the value of coins.id
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coins.id
     *
     * @param id the value for coins.id
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coins.name
     *
     * @return the value of coins.name
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coins.name
     *
     * @param name the value for coins.name
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coins.symbol
     *
     * @return the value of coins.symbol
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coins.symbol
     *
     * @param symbol the value for coins.symbol
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coins.coinmarket_id
     *
     * @return the value of coins.coinmarket_id
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    public Integer getCoinmarketId() {
        return coinmarketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coins.coinmarket_id
     *
     * @param coinmarketId the value for coins.coinmarket_id
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    public void setCoinmarketId(Integer coinmarketId) {
        this.coinmarketId = coinmarketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coins.quantity
     *
     * @return the value of coins.quantity
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    public Double getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coins.quantity
     *
     * @param quantity the value for coins.quantity
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coins.user_id
     *
     * @return the value of coins.user_id
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coins.user_id
     *
     * @param userId the value for coins.user_id
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coins.created_at
     *
     * @return the value of coins.created_at
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coins.created_at
     *
     * @param createdAt the value for coins.created_at
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coins.updated_at
     *
     * @return the value of coins.updated_at
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coins.updated_at
     *
     * @param updatedAt the value for coins.updated_at
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}