package com.allxone.coinmarket.model;

import java.util.Date;

public class Departments {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.id
	 * @mbg.generated  Thu Feb 22 09:13:49 ICT 2024
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.name
	 * @mbg.generated  Thu Feb 22 09:13:49 ICT 2024
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.id
	 * @return  the value of department.id
	 * @mbg.generated  Thu Feb 22 09:13:49 ICT 2024
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.id
	 * @param id  the value for department.id
	 * @mbg.generated  Thu Feb 22 09:13:49 ICT 2024
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.name
	 * @return  the value of department.name
	 * @mbg.generated  Thu Feb 22 09:13:49 ICT 2024
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.name
	 * @param name  the value for department.name
	 * @mbg.generated  Thu Feb 22 09:13:49 ICT 2024
	 */
	public void setName(String name) {
		this.name = name;
	}
}