package com.allxone.coinmarket.model;

public class Holidays {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holidays.id
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holidays.holiday_name
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    private String holidayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holidays.duration_days
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    private Short durationDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holidays.hodiday_description
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    private String hodidayDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holidays.id
     *
     * @return the value of holidays.id
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holidays.id
     *
     * @param id the value for holidays.id
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holidays.holiday_name
     *
     * @return the value of holidays.holiday_name
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    public String getHolidayName() {
        return holidayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holidays.holiday_name
     *
     * @param holidayName the value for holidays.holiday_name
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    public void setHolidayName(String holidayName) {
        this.holidayName = holidayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holidays.duration_days
     *
     * @return the value of holidays.duration_days
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    public Short getDurationDays() {
        return durationDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holidays.duration_days
     *
     * @param durationDays the value for holidays.duration_days
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    public void setDurationDays(Short durationDays) {
        this.durationDays = durationDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holidays.hodiday_description
     *
     * @return the value of holidays.hodiday_description
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    public String getHodidayDescription() {
        return hodidayDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holidays.hodiday_description
     *
     * @param hodidayDescription the value for holidays.hodiday_description
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    public void setHodidayDescription(String hodidayDescription) {
        this.hodidayDescription = hodidayDescription;
    }
}