package com.allxone.coinmarket.model;

import java.math.BigDecimal;

public class InsuranceType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance_type.id
     *
     * @mbg.generated Thu Feb 29 15:51:14 ICT 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance_type.insurance_name
     *
     * @mbg.generated Thu Feb 29 15:51:14 ICT 2024
     */
    private String insuranceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance_type.insurance_rate
     *
     * @mbg.generated Thu Feb 29 15:51:14 ICT 2024
     */
    private BigDecimal insuranceRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance_type.insurance_description
     *
     * @mbg.generated Thu Feb 29 15:51:14 ICT 2024
     */
    private String insuranceDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance_type.id
     *
     * @return the value of insurance_type.id
     *
     * @mbg.generated Thu Feb 29 15:51:14 ICT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance_type.id
     *
     * @param id the value for insurance_type.id
     *
     * @mbg.generated Thu Feb 29 15:51:14 ICT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance_type.insurance_name
     *
     * @return the value of insurance_type.insurance_name
     *
     * @mbg.generated Thu Feb 29 15:51:14 ICT 2024
     */
    public String getInsuranceName() {
        return insuranceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance_type.insurance_name
     *
     * @param insuranceName the value for insurance_type.insurance_name
     *
     * @mbg.generated Thu Feb 29 15:51:14 ICT 2024
     */
    public void setInsuranceName(String insuranceName) {
        this.insuranceName = insuranceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance_type.insurance_rate
     *
     * @return the value of insurance_type.insurance_rate
     *
     * @mbg.generated Thu Feb 29 15:51:14 ICT 2024
     */
    public BigDecimal getInsuranceRate() {
        return insuranceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance_type.insurance_rate
     *
     * @param insuranceRate the value for insurance_type.insurance_rate
     *
     * @mbg.generated Thu Feb 29 15:51:14 ICT 2024
     */
    public void setInsuranceRate(BigDecimal insuranceRate) {
        this.insuranceRate = insuranceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance_type.insurance_description
     *
     * @return the value of insurance_type.insurance_description
     *
     * @mbg.generated Thu Feb 29 15:51:14 ICT 2024
     */
    public String getInsuranceDescription() {
        return insuranceDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance_type.insurance_description
     *
     * @param insuranceDescription the value for insurance_type.insurance_description
     *
     * @mbg.generated Thu Feb 29 15:51:14 ICT 2024
     */
    public void setInsuranceDescription(String insuranceDescription) {
        this.insuranceDescription = insuranceDescription;
    }
}