package com.allxone.coinmarket.model;

import java.math.BigDecimal;
import java.util.Date;

public class Payroll {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payroll.id
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payroll.employee_id
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    private Long employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payroll.salary
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    private BigDecimal salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payroll.bonus
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    private BigDecimal bonus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payroll.deductions
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    private BigDecimal deductions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payroll.net_salary
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    private BigDecimal netSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payroll.period_start
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    private Date periodStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payroll.period_end
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    private Date periodEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payroll.created_at
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payroll.updated_at
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    private Date updatedAt;

    private String holidayIds;

    public String getHolidayIds() {
        return holidayIds;
    }

    public void setHolidayIds(String holidayIds) {
        this.holidayIds = holidayIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payroll.id
     *
     * @return the value of payroll.id
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payroll.id
     *
     * @param id the value for payroll.id
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payroll.employee_id
     *
     * @return the value of payroll.employee_id
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public Long getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payroll.employee_id
     *
     * @param employeeId the value for payroll.employee_id
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payroll.salary
     *
     * @return the value of payroll.salary
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payroll.salary
     *
     * @param salary the value for payroll.salary
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payroll.bonus
     *
     * @return the value of payroll.bonus
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public BigDecimal getBonus() {
        return bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payroll.bonus
     *
     * @param bonus the value for payroll.bonus
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public void setBonus(BigDecimal bonus) {
        this.bonus = bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payroll.deductions
     *
     * @return the value of payroll.deductions
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public BigDecimal getDeductions() {
        return deductions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payroll.deductions
     *
     * @param deductions the value for payroll.deductions
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public void setDeductions(BigDecimal deductions) {
        this.deductions = deductions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payroll.net_salary
     *
     * @return the value of payroll.net_salary
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public BigDecimal getNetSalary() {
        return netSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payroll.net_salary
     *
     * @param netSalary the value for payroll.net_salary
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public void setNetSalary(BigDecimal netSalary) {
        this.netSalary = netSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payroll.period_start
     *
     * @return the value of payroll.period_start
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public Date getPeriodStart() {
        return periodStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payroll.period_start
     *
     * @param periodStart the value for payroll.period_start
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public void setPeriodStart(Date periodStart) {
        this.periodStart = periodStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payroll.period_end
     *
     * @return the value of payroll.period_end
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public Date getPeriodEnd() {
        return periodEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payroll.period_end
     *
     * @param periodEnd the value for payroll.period_end
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public void setPeriodEnd(Date periodEnd) {
        this.periodEnd = periodEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payroll.created_at
     *
     * @return the value of payroll.created_at
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payroll.created_at
     *
     * @param createdAt the value for payroll.created_at
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payroll.updated_at
     *
     * @return the value of payroll.updated_at
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payroll.updated_at
     *
     * @param updatedAt the value for payroll.updated_at
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}