package com.allxone.coinmarket.model;

import java.math.BigDecimal;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder

public class TaxInformation {
  /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tax_information.id
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tax_information.employee_id
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	private Long employeeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tax_information.tax_rate
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	private BigDecimal taxRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tax_information.tax_exemption
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	private Boolean taxExemption;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tax_information.created_at
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tax_information.updated_at
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tax_information.status
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	private Boolean status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tax_information.date_start
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	private Date dateStart;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tax_information.id
	 * @return  the value of tax_information.id
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tax_information.id
	 * @param id  the value for tax_information.id
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tax_information.employee_id
	 * @return  the value of tax_information.employee_id
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	public Long getEmployeeId() {
		return employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tax_information.employee_id
	 * @param employeeId  the value for tax_information.employee_id
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	public void setEmployeeId(Long employeeId) {
		this.employeeId = employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tax_information.tax_rate
	 * @return  the value of tax_information.tax_rate
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	public BigDecimal getTaxRate() {
		return taxRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tax_information.tax_rate
	 * @param taxRate  the value for tax_information.tax_rate
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	public void setTaxRate(BigDecimal taxRate) {
		this.taxRate = taxRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tax_information.tax_exemption
	 * @return  the value of tax_information.tax_exemption
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	public Boolean getTaxExemption() {
		return taxExemption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tax_information.tax_exemption
	 * @param taxExemption  the value for tax_information.tax_exemption
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	public void setTaxExemption(Boolean taxExemption) {
		this.taxExemption = taxExemption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tax_information.created_at
	 * @return  the value of tax_information.created_at
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tax_information.created_at
	 * @param createdAt  the value for tax_information.created_at
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tax_information.updated_at
	 * @return  the value of tax_information.updated_at
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tax_information.updated_at
	 * @param updatedAt  the value for tax_information.updated_at
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tax_information.status
	 * @return  the value of tax_information.status
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	public Boolean getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tax_information.status
	 * @param status  the value for tax_information.status
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	public void setStatus(Boolean status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tax_information.date_start
	 * @return  the value of tax_information.date_start
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	public Date getDateStart() {
		return dateStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tax_information.date_start
	 * @param dateStart  the value for tax_information.date_start
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	public void setDateStart(Date dateStart) {
		this.dateStart = dateStart;
	}


}