package com.allxone.coinmarket.model;

import java.math.BigDecimal;
import java.util.Date;

public class TimeTracking {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_tracking.id
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_tracking.employee_id
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    private Long employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_tracking.date_track
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    private Date dateTrack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_tracking.clock_in
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    private Date clockIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_tracking.clock_out
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    private Date clockOut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_tracking.total_hours
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    private BigDecimal totalHours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_tracking.created_at
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_tracking.updated_at
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_tracking.id
     *
     * @return the value of time_tracking.id
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_tracking.id
     *
     * @param id the value for time_tracking.id
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_tracking.employee_id
     *
     * @return the value of time_tracking.employee_id
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public Long getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_tracking.employee_id
     *
     * @param employeeId the value for time_tracking.employee_id
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_tracking.date_track
     *
     * @return the value of time_tracking.date_track
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public Date getDateTrack() {
        return dateTrack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_tracking.date_track
     *
     * @param dateTrack the value for time_tracking.date_track
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public void setDateTrack(Date dateTrack) {
        this.dateTrack = dateTrack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_tracking.clock_in
     *
     * @return the value of time_tracking.clock_in
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public Date getClockIn() {
        return clockIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_tracking.clock_in
     *
     * @param clockIn the value for time_tracking.clock_in
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public void setClockIn(Date clockIn) {
        this.clockIn = clockIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_tracking.clock_out
     *
     * @return the value of time_tracking.clock_out
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public Date getClockOut() {
        return clockOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_tracking.clock_out
     *
     * @param clockOut the value for time_tracking.clock_out
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public void setClockOut(Date clockOut) {
        this.clockOut = clockOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_tracking.total_hours
     *
     * @return the value of time_tracking.total_hours
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public BigDecimal getTotalHours() {
        return totalHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_tracking.total_hours
     *
     * @param totalHours the value for time_tracking.total_hours
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public void setTotalHours(BigDecimal totalHours) {
        this.totalHours = totalHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_tracking.created_at
     *
     * @return the value of time_tracking.created_at
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_tracking.created_at
     *
     * @param createdAt the value for time_tracking.created_at
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_tracking.updated_at
     *
     * @return the value of time_tracking.updated_at
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_tracking.updated_at
     *
     * @param updatedAt the value for time_tracking.updated_at
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}