package com.allxone.coinmarket.mapper;

import com.allxone.coinmarket.model.Coins;
import com.allxone.coinmarket.model.CoinsExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CoinsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coins
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    long countByExample(CoinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coins
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    int deleteByExample(CoinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coins
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coins
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    int insert(Coins row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coins
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    int insertSelective(Coins row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coins
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    List<Coins> selectByExample(CoinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coins
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    Coins selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coins
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    int updateByExampleSelective(@Param("row") Coins row, @Param("example") CoinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coins
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    int updateByExample(@Param("row") Coins row, @Param("example") CoinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coins
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    int updateByPrimaryKeySelective(Coins row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coins
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    int updateByPrimaryKey(Coins row);

    List<Coins> selectAllCoinsByUserId(Long userId);
}