package com.allxone.coinmarket.mapper;

import com.allxone.coinmarket.model.Departments;
import com.allxone.coinmarket.model.DepartmentsExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface DepartmentsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbg.generated  Thu Feb 22 09:13:49 ICT 2024
	 */
	long countByExample(DepartmentsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbg.generated  Thu Feb 22 09:13:49 ICT 2024
	 */
	int deleteByExample(DepartmentsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbg.generated  Thu Feb 22 09:13:49 ICT 2024
	 */
	int insert(Departments row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbg.generated  Thu Feb 22 09:13:49 ICT 2024
	 */
	int insertSelective(Departments row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbg.generated  Thu Feb 22 09:13:49 ICT 2024
	 */
	List<Departments> selectByExample(DepartmentsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbg.generated  Thu Feb 22 09:13:49 ICT 2024
	 */
	int updateByExampleSelective(@Param("row") Departments row, @Param("example") DepartmentsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbg.generated  Thu Feb 22 09:13:49 ICT 2024
	 */
	int updateByExample(@Param("row") Departments row, @Param("example") DepartmentsExample example);
}