package com.allxone.coinmarket.mapper;

import com.allxone.coinmarket.model.Holidays;
import com.allxone.coinmarket.model.HolidaysExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HolidaysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    long countByExample(HolidaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    int deleteByExample(HolidaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    int insert(Holidays row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    int insertSelective(Holidays row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    List<Holidays> selectByExampleWithBLOBs(HolidaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    List<Holidays> selectByExample(HolidaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    Holidays selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    int updateByExampleSelective(@Param("row") Holidays row, @Param("example") HolidaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    int updateByExampleWithBLOBs(@Param("row") Holidays row, @Param("example") HolidaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    int updateByExample(@Param("row") Holidays row, @Param("example") HolidaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    int updateByPrimaryKeySelective(Holidays row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    int updateByPrimaryKeyWithBLOBs(Holidays row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    int updateByPrimaryKey(Holidays row);
}