package com.allxone.coinmarket.mapper;

import com.allxone.coinmarket.model.Holidays;
import com.allxone.coinmarket.model.HolidaysExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface HolidaysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Thu Feb 29 15:51:14 ICT 2024
     */
    long countByExample(HolidaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Thu Feb 29 15:51:14 ICT 2024
     */
    int deleteByExample(HolidaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Thu Feb 29 15:51:14 ICT 2024
     */
    int insert(Holidays row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Thu Feb 29 15:51:14 ICT 2024
     */
    int insertSelective(Holidays row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Thu Feb 29 15:51:14 ICT 2024
     */
    List<Holidays> selectByExampleWithBLOBs(HolidaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Thu Feb 29 15:51:14 ICT 2024
     */
    List<Holidays> selectByExample(HolidaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Thu Feb 29 15:51:14 ICT 2024
     */
    int updateByExampleSelective(@Param("row") Holidays row, @Param("example") HolidaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Thu Feb 29 15:51:14 ICT 2024
     */
    int updateByExampleWithBLOBs(@Param("row") Holidays row, @Param("example") HolidaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holidays
     *
     * @mbg.generated Thu Feb 29 15:51:14 ICT 2024
     */
    int updateByExample(@Param("row") Holidays row, @Param("example") HolidaysExample example);
}