package com.allxone.coinmarket.mapper;

import com.allxone.coinmarket.model.insuranceType;
import com.allxone.coinmarket.model.insuranceTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface insuranceTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance_type
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    long countByExample(insuranceTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance_type
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    int deleteByExample(insuranceTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance_type
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance_type
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    int insert(insuranceType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance_type
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    int insertSelective(insuranceType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance_type
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    List<insuranceType> selectByExampleWithBLOBs(insuranceTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance_type
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    List<insuranceType> selectByExample(insuranceTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance_type
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    insuranceType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance_type
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    int updateByExampleSelective(@Param("row") insuranceType row, @Param("example") insuranceTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance_type
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    int updateByExampleWithBLOBs(@Param("row") insuranceType row, @Param("example") insuranceTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance_type
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    int updateByExample(@Param("row") insuranceType row, @Param("example") insuranceTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance_type
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    int updateByPrimaryKeySelective(insuranceType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance_type
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    int updateByPrimaryKeyWithBLOBs(insuranceType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance_type
     *
     * @mbg.generated Fri Mar 01 09:36:59 ICT 2024
     */
    int updateByPrimaryKey(insuranceType row);
}