package com.allxone.coinmarket.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.allxone.coinmarket.dto.response.PayrollDTO;
import com.allxone.coinmarket.model.Payroll;
import com.allxone.coinmarket.model.PayrollExample;
@Mapper
public interface PayrollMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    long countByExample(PayrollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int deleteByExample(PayrollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int insert(Payroll row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int insertSelective(Payroll row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    List<Payroll> selectByExample(PayrollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    Payroll selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int updateByExampleSelective(@Param("row") Payroll row, @Param("example") PayrollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int updateByExample(@Param("row") Payroll row, @Param("example") PayrollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int updateByPrimaryKeySelective(Payroll row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int updateByPrimaryKey(Payroll row);

    List<Payroll> getAllPayrolls( Integer month);

    List<PayrollDTO> getAllSalary(@Param("month") Integer month);

    List<PayrollDTO> getAllSalaryByFirstName(@Param("month") Integer month, @Param("firstname") String firstname);

    Payroll getEmployeeSalaryByMonth(@Param("month") Integer month, @Param("employeeId") Long employeeId);

    List<Payroll> getTopThreeLatestSalaries(@Param("employeeId") Long employeeId);
    BigDecimal sumSalaryByMonth(PayrollExample payrollExample);

    List<Object> calcNetSalary(@Param("list") List<Integer> listId,@Param("monthFrom") Integer monthFrom, @Param("monthTo") Integer monthTo, @Param("yearFrom") Integer yearFrom, @Param("yearTo") Integer yearTo);
}