package com.allxone.coinmarket.mapper;

import com.allxone.coinmarket.model.Payroll;
import com.allxone.coinmarket.model.PayrollExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayrollMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    long countByExample(PayrollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int deleteByExample(PayrollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int insert(Payroll row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int insertSelective(Payroll row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    List<Payroll> selectByExample(PayrollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    Payroll selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int updateByExampleSelective(@Param("row") Payroll row, @Param("example") PayrollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int updateByExample(@Param("row") Payroll row, @Param("example") PayrollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int updateByPrimaryKeySelective(Payroll row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payroll
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int updateByPrimaryKey(Payroll row);
}