package com.allxone.coinmarket.mapper;

import com.allxone.coinmarket.model.Roles;
import com.allxone.coinmarket.model.RolesExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    long countByExample(RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    int deleteByExample(RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    int insert(Roles row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    int insertSelective(Roles row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    List<Roles> selectByExample(RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    Roles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    int updateByExampleSelective(@Param("row") Roles row, @Param("example") RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    int updateByExample(@Param("row") Roles row, @Param("example") RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    int updateByPrimaryKeySelective(Roles row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    int updateByPrimaryKey(Roles row);
}