package com.allxone.coinmarket.mapper;

import com.allxone.coinmarket.model.TaxInformation;
import com.allxone.coinmarket.model.TaxInformationExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TaxInformationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tax_information
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	long countByExample(TaxInformationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tax_information
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	int deleteByExample(TaxInformationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tax_information
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tax_information
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	int insert(TaxInformation row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tax_information
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	int insertSelective(TaxInformation row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tax_information
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	List<TaxInformation> selectByExample(TaxInformationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tax_information
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	TaxInformation selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tax_information
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	int updateByExampleSelective(@Param("row") TaxInformation row, @Param("example") TaxInformationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tax_information
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	int updateByExample(@Param("row") TaxInformation row, @Param("example") TaxInformationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tax_information
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	int updateByPrimaryKeySelective(TaxInformation row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tax_information
	 * @mbg.generated  Tue Mar 05 14:49:58 ICT 2024
	 */
	int updateByPrimaryKey(TaxInformation row);
	
	List<TaxInformation> findByEmployees(Long id,int status);
	
	List<TaxInformation> selectTaxInformation(Long id);
}