package com.allxone.coinmarket.mapper;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.allxone.coinmarket.dto.response.WorkingTimeDTO;
import com.allxone.coinmarket.model.TimeTracking;
import com.allxone.coinmarket.model.TimeTrackingExample;
@Mapper
public interface TimeTrackingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_tracking
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    long countByExample(TimeTrackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_tracking
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int deleteByExample(TimeTrackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_tracking
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_tracking
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int insert(TimeTracking row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_tracking
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int insertSelective(TimeTracking row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_tracking
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    List<TimeTracking> selectByExample(TimeTrackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_tracking
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    TimeTracking selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_tracking
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int updateByExampleSelective(@Param("row") TimeTracking row, @Param("example") TimeTrackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_tracking
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int updateByExample(@Param("row") TimeTracking row, @Param("example") TimeTrackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_tracking
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int updateByPrimaryKeySelective(TimeTracking row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_tracking
     *
     * @mbg.generated Thu Feb 22 09:13:49 ICT 2024
     */
    int updateByPrimaryKey(TimeTracking row);

    BigDecimal sumTotalHours(@Param("employee_id") Long employee_id);

    List<TimeTracking> getEmployeeIdWorkingTime(@Param("employee_id") Long id, @Param("month") int month);
    List<WorkingTimeDTO> findAllWorkingTimeEmployee(@Param("date") Date date,@Param("limit") Integer limit);

    List<WorkingTimeDTO> findAllWorkingTimeEmployeeAllTime(@Param("limit") Integer limit);
}