package com.allxone.coinmarket.mapper;

import com.allxone.coinmarket.model.Users;
import com.allxone.coinmarket.model.UsersExample;
import com.allxone.coinmarket.model.UsersKey;
import com.allxone.coinmarket.model.UsersWithBLOBs;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UsersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Thu Jan 25 09:56:51 ICT 2024
	 */
	long countByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Thu Jan 25 09:56:51 ICT 2024
	 */
	int deleteByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Thu Jan 25 09:56:51 ICT 2024
	 */
	int insert(Users row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Thu Jan 25 09:56:51 ICT 2024
	 */
	int insertSelective(Users row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Thu Jan 25 09:56:51 ICT 2024
	 */
	List<Users> selectByExampleWithBLOBs(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Thu Jan 25 09:56:51 ICT 2024
	 */
	List<Users> selectByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Thu Jan 25 09:56:51 ICT 2024
	 */
	int updateByExampleSelective(@Param("row") Users row, @Param("example") UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Thu Jan 25 09:56:51 ICT 2024
	 */
	int updateByExampleWithBLOBs(@Param("row") Users row, @Param("example") UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Thu Jan 25 09:56:51 ICT 2024
	 */
	int updateByExample(@Param("row") Users row, @Param("example") UsersExample example);
	
	Users findUserByEmail(String email);
	
	Users findUserByUsername(String userName);

	int updateUserById(@Param("row")Users user);

	List<Users> findAllUser();
}