package com.allxone.coinmarket.mapper;

import com.allxone.coinmarket.model.UserRole;
import com.allxone.coinmarket.model.UserRoleExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    long countByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    int deleteByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    int insert(UserRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    int insertSelective(UserRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    List<UserRole> selectByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    int updateByExampleSelective(@Param("row") UserRole row, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Thu Jan 25 09:56:51 ICT 2024
     */
    int updateByExample(@Param("row") UserRole row, @Param("example") UserRoleExample example);
    
    List<UserRole> findRoleByUserId(Long id);
}