
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CRUDAllXone
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: duolingobasicbackenduserservice
coinmarketcap-data:
  api:
    url: https://api.coinmarketcap.com/data-api/v3/cryptocurrency
springdoc:
  use-fqn: true
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
server:
  port: 5555



