spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CRUDAllXone
    username: admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  mail:
    host: smtp.gmail.com
    port: 587
    username: buithang12396@gmail.com
    password: xudnhajooqvwvpit
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.allxone.mybatisprojectbackend.model
coinmarketcap-data:
  api:
    url: https://api.coinmarketcap.com/data-api/v3/cryptocurrency
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5971
      expiration: 86400000
      refresh-token:
        expiration: 604800000
springdoc:
  use-fqn: true
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
server:
  port: 5555
#security:
#  firebase-props:
#    database-url:
#    enable-strict-server-session: false
#    enable-check-session-revoked: false
#    enable-logout-everywhere: false
#    session-expiry-in-days: 5
#  cookie-props:
#    max-age-in-minutes: 7200
#    http-only: true
#    secure: true
#    domain: ${DOMAIN}
#    path: /
#  allow-credentials: true
#  allowed-origins:
#    - http://localhost:3000
#  allowed-methods:
#    - GET
#    - POST
#    - PUT
#    - PATCH
#    - DELETE
#    - OPTIONS
#  allowed-headers:
#    - Authorization
#    - Origin
#    - Content-Type
#    - Accept
#    - Accept-Encoding
#    - Accept-Language
#    - Access-Control-Allow-Origin
#    - Access-Control-Allow-Headers
#    - Access-Control-Request-Method
#    - X-Requested-With
#    - X-Auth-Token
#    - X-Xsrf-Token
#    - Cache-Control
#    - Id-Token
#  allowed-public-apis:
#    - /favicon.ico
#    - /session/login
#    - /public/**
#  exposed-headers:
#    - X-Xsrf-Token



