spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CRUDAllXone
    username: admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.allxone.mybatisprojectbackend.model
coinmarketcap-data:
  api:
    url: https://api.coinmarketcap.com/data-api/v3/cryptocurrency
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5971
      expiration: 86400000
      refresh-token:
        expiration: 604800000
springdoc:
  use-fqn: true
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
server:
  port: 5555



